In [2]:
import yfinance as yf

ticker = "2330.TW"  # 台積電

df = yf.download(
    ticker,
    start="2020-01-01",
    end="2024-12-31",
    interval="1d",
    auto_adjust=False
)

df.tail()

[*********************100%***********************]  1 of 1 completed

Price         Adj Close   Close    High     Low    Open    Volume
Ticker          2330.TW 2330.TW 2330.TW 2330.TW 2330.TW   2330.TW
Date
2024-12-24  1056.366455  1080.0  1095.0  1080.0  1095.0  26461906
2024-12-25  1061.257080  1085.0  1090.0  1080.0  1090.0  15481622
2024-12-26  1061.257080  1085.0  1090.0  1085.0  1085.0  14374900
2024-12-27  1066.147705  1090.0  1095.0  1080.0  1080.0  24948385
2024-12-30  1066.147705  1090.0  1095.0  1085.0  1090.0  23954634

In [3]:
df = yf.download(
    "2330.TW",
    period="5d",
    interval="1d",
    auto_adjust=False
)
df

[*********************100%***********************]  1 of 1 completed

Price      Adj Close   Close    High     Low    Open    Volume
Ticker       2330.TW 2330.TW 2330.TW 2330.TW 2330.TW   2330.TW
Date
2026-06-29    2370.0  2370.0  2395.0  2330.0  2330.0  33267315
2026-06-30    2410.0  2410.0  2475.0  2410.0  2440.0  42933128
2026-07-01    2505.0  2505.0  2505.0  2475.0  2495.0  30489002
2026-07-02    2465.0  2465.0  2480.0  2445.0  2450.0  27485121
2026-07-03    2445.0  2445.0  2465.0  2415.0  2415.0  26489446

In [4]:
close_df = df['Close'].reset_index()
close_df

Ticker       Date  2330.TW
0      2026-06-29   2370.0
1      2026-06-30   2410.0
2      2026-07-01   2505.0
3      2026-07-02   2465.0
4      2026-07-03   2445.0

In [ ]:
import yfinance as yf
import pandas as pd

tickers = {
    "台積電": "2330.TW",
    "聯電": "2303.TW",
    "聯發科": "2454.TW",
    "鴻海": "2317.TW",
}

# 抓 2026 年至今的歷史資料
data = yf.download(
    list(tickers.values()),
    start = "2026-01-01",
    interval = "1d",
    auto_adjust = True
)

# 只取收盤價
close = data["Close"]

# 把欄位名稱從股票代號改成中文公司名 
# comprehensions語法，快速生成list dict的方法
code_to_name = {v: k for k, v in tickers.items()}
close = close.rename(columns=code_to_name)

print("收盤價：")
print(close.tail())

# 計算每日報酬率
returns = close.pct_change().dropna()

# 計算相關係數
corr = returns.corr()

print("\n日報酬率相關係數：")
corr

# 如果想存檔
#close.to_csv("taiwan_stocks_close_2026_to_now.csv", encoding="utf-8-sig")
#returns.to_csv("taiwan_stocks_returns_2026_to_now.csv", encoding="utf-8-sig")
#corr.to_csv("taiwan_stocks_correlation.csv", encoding="utf-8-sig")

[*********************100%***********************]  4 of 4 completed

收盤價：
Ticker         聯電          鴻海     台積電     聯發科
Date
2026-06-29  164.0  239.371582  2370.0  3910.0
2026-06-30  164.5  243.741455  2410.0  4245.0
2026-07-01  169.0  240.828217  2505.0  4335.0
2026-07-02  165.5  239.000000  2465.0  4345.0
2026-07-03  170.5  240.500000  2445.0  4195.0

日報酬率相關係數：

Ticker        聯電        鴻海       台積電       聯發科
Ticker
聯電      1.000000  0.284395  0.321617  0.327949
鴻海      0.284395  1.000000  0.559397  0.505672
台積電     0.321617  0.559397  1.000000  0.411458
聯發科     0.327949  0.505672  0.411458  1.000000

In [7]:
word = 'letters'
for n in word:
    print(n)

l
e
t
t
e
r
s